title: סטודיו משלך
url: https://studioofherown.com
enforce_ssl: studioofherown.com
permalink: /:category/:title
assets: /assets/
github: [metadata]
repository: studioofherown/studioofherown.github.io
timezone: UTC
safe: true
theme: false
future: true
collections:
    pages:
        output: true
        permalink: /:path
        lang: en
langs:
    - en
    - he
defaults:
    -
        scope:
            path: ""
            type: pages
        values:
            lang: en
    -
        scope:
            path: _pages/en
            type: pages
        values:
            lang: en
    -
        scope:
            path: _pages/he
            type: pages
        values:
            lang: he
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: true
sass:
    sass_dir: assets
    style: compressed
compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
    profile: false
    startings: [html, head, body]
exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - node_modules
    - /*README.md
    - .*
    - ~*
