title: סטודיו משלך
url: https://studioofherown.com
enforce_ssl: studioofherown.com
permalink: /:category/:title
assets: /assets/
timezone: UTC
safe: true
theme: false
future: true
include: [_pages]
collections:
    pages:
        output: true
        permalink: /:path
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: true
sass:
    sass_dir: assets
    style: compressed
compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
    profile: false
    startings: [html, head, body]
exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - node_modules
    - /*README.md
    - ~*
