# GitHub pages https://pages.github.com/versions/

# include: ['_pages']
# encoding: utf-8
timezone: UTC
markdown: kramdown
permalink: /:categories/:title
sass:
    style: compressed

# port: 80
url: https://studioofherown.com
enforce_ssl: studioofherown.com
email: team@studioofherown.com

title: סטודיו משלך
description: סטודיו משלך הוא מיזם חברתי-מגדרי הפועל בירושלים והוקם על מנת לתמוך באמניות צעירות בתחילת דרכן
