artist:
    email: מייל
    website: פורטפוליו
    statement: הצהרה
exhibition:
    - name: curator
      title: אוצר
    - name: address
      title: כתובת
    - name: participators
      title: משתתפות
      short: true
    - name: catalog
      title: קטלוג
publication:
    - name: link
      title: קישור למאמר
